/* Author: Terry Mao
 * Purpose: Cause the M.O.H.B told me Workshop Part 2
 * Date: July 4, 2015
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TeamWorkshop2_Part2
{
    // make public class Product
    public class Product
    {
        // provide public properties for access
        public Product() { }

        public int ProductId { get; set; }

        public string ProdName { get; set; }
    }
}
